### ISSUE TITLE
/demo/srv6/end.am cannot be operated correctly

### ISSUE THREAD

**Issue by foresnail** [ebiken/p4srv6#6]
> ~$ ./p4/behavioral-model/tools/runtime_CLI.py
> action end_am(PortId_t oif, EthernetAddress dmac)
>   oif=3, dmac=<mac addr of veth3>, priority=100(required for ternary table)
> action end_am_d(PortId_t oif)
>   oif=2

What does the piece of code mean?  I have strictly followed the instructions except this unknown code and  I cannot operate the demo of /demo/srv6/end.am correctly. Could you explain this code in detail? 
(ps. I can operate the demo of l2fwd corrrectly with the instructions and my enviroments is ok)
Looking forward to your reply~

**Comment by ebiken** [comment]
Hi. It's just an explanation of parameters of the `table_add` commands following them mean.
You only need to run the commands after `$runtime_CLI.py` and not the comments starting with `>`
```
$ runtime_CLI.py
table_add srv6_end end_am 0xfd0100000000000000000000000000ff&&&0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF => 3 0x561f6aa0de06 100
table_add srv6_end_iif end_am_d 3 => 2
```
